server:
  port : 8090

 

spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-54-197-254-117.compute-1.amazonaws.com:5432/d16v54qftorbkj
        username: hxplhsuygfcmqn
        password: dac8d0a71de0c7d82682ed2149299e23499dd39ce0f08d316a23afdfd082dd34
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

 

    jpa: 
        hibernate:
            ddl-auto: create-drop